import { JetBrains_Mono, Tinos } from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';

const jetbrains = JetBrains_Mono({
	variable: '--font-jetbrains-mono',
	subsets: ['latin'],
});

const tinos = Tinos({ variable: '--font-tinos', subsets: ['latin'], weight: '400' });

export const metadata = {
	title: 'tqy',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html
			lang='en'
			className={cn(
				'h-full',
				'antialiased',
				jetbrains.variable,
				'font-sans',
				tinos.variable,
			)}
		>
			<body className='min-h-full flex flex-col items-center'>{children}</body>
		</html>
	);
}
