import {
	JetBrains_Mono,
	Libre_Barcode_128_Text,
	Tinos,
} from 'next/font/google';
import './globals.css';
import { cn } from '@/lib/utils';
import Script from 'next/script';
import { ThemeProvider } from '@wrksz/themes/next';
import NavBar from '@/components/modules/nav-bar';

const jetbrains = JetBrains_Mono({
	variable: '--font-jetbrains-mono',
	subsets: ['latin'],
});

const tinos = Tinos({
	variable: '--font-tinos',
	subsets: ['latin'],
	weight: '400',
});

const libreBarcode = Libre_Barcode_128_Text({
	variable: '--font-barcode',
	weight: '400',
});

export const metadata = {
	title: 'Tan Qi Yang',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {

	return (
		<html
			lang='en'
			className={cn(
				'h-full',
				'antialiased',
				jetbrains.variable,
				'font-sans',
				tinos.variable,
				libreBarcode.variable,
			)}
			suppressHydrationWarning
		>
			<body className='min-h-full flex flex-col items-center'>
				<ThemeProvider>
					<NavBar />
					{children}
				</ThemeProvider>{' '}
				<Script
					src='https://cloud.umami.is/script.js'
					data-website-id='82499b45-9a5c-4e62-9e94-6df3c5106f92'
				/>
			</body>
		</html>
	);
}
